gen-dash:
	jsonnet grafana/dashboards/server.libsonnet -J grafana/dashboards/vendor/ -o grafana/dashboards/output/server.json
	jsonnet grafana/dashboards/signals.libsonnet -J grafana/dashboards/vendor/ -o grafana/dashboards/output/signals.json